//CBTIS 89
// CRISTHIAN MOLINA RAMOS
// PROGRAMACION 2A
// PROGRAMA PARA CALCULAR e imprimir 
// EL SUELDO SEMANAL DE UN TRABAJADOR
Definir NOMBRE DEL EMPLEADO , SUELDO DIARIO , HORAS EXTRAS,Como Entero
ESCRIBIR "HORAS EXTRAS"
Leer  HORAS EXTRAS
ESCRIBIR "SUELDO DIARIO"
Leer SUELDO DIARIO
ESCRIBIR "NOMBRE DEL EMPLEADO"
Leer NOMBRE DEL EMPLEADO


Algoritmo sin_titulo
	
FinAlgoritmo
