//CBTIS89
//PROGRAMACION 2A T.M.
//BRAYAN DANIEL GALINDO GONZALEZ
//PROGRAMA QUE CALCULA SI UN EMPLEADO TRABAJO HORAS EXTRA Y CUANTO SE LE PAGARA
Algoritmo Examen1_GGB
	definir SD,NHT,NDE,SF,HE Como Entero
	ESCRIBIR "DAME SU SUELDO DIARIO"
	LEER SD
	ESCRIBIR "DAME SUS HORAS TRABAJADAS EN LA SEMANA"
	LEER NHT
	Si NHT>40 Entonces
		
	SiNo
		ESCRIBIR "NO TRABAJO HORAS EXTRAS"
		
		
	Fin Si
FinAlgoritmo
